In [93]:
#imports 

import os
import sys

from PIL import Image
import numpy as np

from skimage import io, color, filters


In [94]:
#Constants:
#data wd:
WD = '/Users/nikhilarora/data/fydp/sb_images'


In [87]:
img_car = io.imread(os.path.join(WD + '/IMG_9769.JPG'))
#img_car = np.uint8(color.rgb2gray(img_car) * 255)
print(img_car.shape)
img_ncar = io.imread(WD + '/IMG_9769.JPG')

(3024, 4032, 3)


In [88]:
threshold_value = filters.threshold_otsu(img_car)
threshold_value

/Users/nikhilarora/anaconda/lib/python3.6/site-packages/skimage/filters/thresholding.py:271: UserWarning: threshold_otsu is expected to work correctly only for grayscale images; image shape (3024, 4032, 3) looks like an RGB image
  warn(msg.format(image.shape))


118

In [89]:
print(img_car.shape)
print(img_ncar.shape)

(3024, 4032, 3)
(3024, 4032, 3)


In [90]:
display_car = Image.fromarray(img_car, 'RGB') #print greyscale image...
#display_ncar = Image.fromarray(img_ncar)
display_car.show()
#display_ncar.show()

In [92]:
print(img_car)

[[[132 121  93]
  [130 119  91]
  [126 115  87]
  ..., 
  [157 146 118]
  [156 145 117]
  [156 145 117]]

 [[126 115  87]
  [124 113  85]
  [125 114  86]
  ..., 
  [155 144 116]
  [154 143 115]
  [155 144 116]]

 [[123 112  84]
  [122 111  83]
  [123 112  84]
  ..., 
  [158 147 119]
  [157 146 118]
  [156 145 117]]

 ..., 
 [[123 112  94]
  [124 113  95]
  [122 114  95]
  ..., 
  [130 119 101]
  [132 121 103]
  [136 124 108]]

 [[123 112  94]
  [124 113  95]
  [123 115  96]
  ..., 
  [130 119 101]
  [131 120 102]
  [133 121 105]]

 [[121 110  92]
  [121 113  94]
  [122 114  95]
  ..., 
  [132 121 103]
  [130 119 101]
  [131 119 103]]]
